#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
// Turns the linked program blob (program.elf, linked -pie by
// pebble_program.ld) into C source the shell compiles into the app image:
// the program's memory as one initialized, writable array (the image, then
// its .bss as zeros), and its relocation offsets.
//
// Being part of the app image, the program is loaded by PebbleOS with the
// rest of the app, into memory the firmware makes executable; the shell only
// patches data words (the relocations). The image is capped at 64 KB
// (`PebbleProcessInfo.load_size` is a uint16_t), which today's programs fit.
//
// A static -pie link resolves every symbol, so the only dynamic relocation it
// can leave is R_ARM_RELATIVE: "add the load address to this word". Anything
// else means the image depends on a symbol nobody will bind, and the blob
// would crash on its first use of it -- so it is refused here, at build time.
import { execFileSync } from 'node:child_process'
import { readFileSync, unlinkSync, writeFileSync } from 'node:fs'
import path from 'node:path'

const [elf, out, toolchainBin] = process.argv.slice(2)
if (!elf || !out || !toolchainBin) {
  console.error('usage: pack-program.mjs <program.elf> <out.c> <arm-none-eabi bin dir>')
  process.exit(2)
}
const tool = (name) => path.join(toolchainBin, `arm-none-eabi-${name}`)
const run = (name, args) => execFileSync(tool(name), args, { encoding: 'utf8', maxBuffer: 64 << 20 })

const MAGIC = 0x50414547 // "GEAP", GEA_PEBBLE_PROGRAM_MAGIC
const ABI = 1 // GEA_PEBBLE_ABI

const symbols = new Map()
for (const line of run('nm', [elf]).split('\n')) {
  const [address, , name] = line.trim().split(/\s+/)
  if (name) symbols.set(name, Number.parseInt(address, 16))
}
const imageEnd = symbols.get('__gea_image_end')
const memoryEnd = symbols.get('__gea_memory_end')
if (imageEnd === undefined || memoryEnd === undefined) throw new Error(`${elf}: not linked with pebble_program.ld`)
if (symbols.get('gea_pebble_program') !== 0) throw new Error(`${elf}: the program header is not at offset 0`)

// A store-exclusive to app RAM never succeeds on the Pebble Time 2 (SF32LB52),
// so any LDREX/STREX retry loop -- an atomic from libstdc++ or libgcc -- hangs
// the app on the watch while it runs in the emulator. Refused here.
const exclusive = new Set()
let fn = ''
for (const line of run('objdump', ['-d', elf]).split('\n')) {
  const head = line.match(/^[0-9a-f]+ <([^>]+)>:/)
  if (head) fn = head[1]
  else if (/\t(ldrex|strex|clrex)/.test(line)) exclusive.add(fn)
}
if (exclusive.size) throw new Error(`${elf}: exclusive access (LDREX/STREX), which hangs on the Pebble Time 2, in ${[...exclusive].join(', ')}`)

const relocs = []
let inDynamic = false
for (const line of run('readelf', ['-rW', elf]).split('\n')) {
  const section = line.match(/^Relocation section '([^']+)'/)
  if (section) {
    inDynamic = section[1] === '.rel.dyn'
    continue
  }
  if (!inDynamic) continue
  const fields = line.trim().split(/\s+/)
  if (!/^[0-9a-f]{8}$/.test(fields[0] ?? '')) continue
  if (fields[2] !== 'R_ARM_RELATIVE') throw new Error(`${elf}: unsupported dynamic relocation ${fields[2]} at 0x${fields[0]} (${fields.slice(4).join(' ')})`)
  const offset = Number.parseInt(fields[0], 16)
  if (offset + 4 > imageEnd || offset % 4 !== 0) throw new Error(`${elf}: relocation at 0x${fields[0]} lies outside the image`)
  relocs.push(offset)
}

// objcopy writes every loadable section from address 0; .bss is NOLOAD and
// .rel.dyn sits past it, so the file is cut back to the image.
const flat = `${out}.flat`
run('objcopy', ['-O', 'binary', '-R', '.rel.dyn', '-R', '.bss', elf, flat])
const raw = readFileSync(flat)
unlinkSync(flat)
const image = Buffer.alloc(imageEnd)
raw.copy(image, 0, 0, Math.min(raw.length, imageEnd))

const words = (buffer) => {
  const out = []
  for (let i = 0; i < buffer.length; i += 4) out.push(`0x${buffer.readUInt32LE(i).toString(16)}u`)
  return out
}
const lines = (items, perLine) => {
  const out = []
  for (let i = 0; i < items.length; i += perLine) out.push(`\t${items.slice(i, i + perLine).join(', ')},`)
  return out.join('\n')
}
const memoryWords = Math.ceil(memoryEnd / 4)
const memory = Buffer.alloc(memoryWords * 4)
image.copy(memory)
writeFileSync(
  out,
  `// Generated by pack-program.mjs from ${path.basename(elf)}; do not edit.
#include <stdint.h>

#define GEA_PEBBLE_PROGRAM_IMAGE_SIZE ${imageEnd}u
#define GEA_PEBBLE_PROGRAM_MEMORY_SIZE ${memoryEnd}u
#define GEA_PEBBLE_PROGRAM_RELOC_COUNT ${relocs.length}u

// Writable (.data), so the image the firmware loads is the program's memory.
__attribute__((aligned(8))) static uint32_t gea_program_memory[${memoryWords}] = {
${lines(words(memory), 8)}
};

static const uint32_t gea_program_relocs[${Math.max(relocs.length, 1)}] = {
${relocs.length ? lines(relocs.map((offset) => `0x${offset.toString(16)}u`), 8) : '\t0,'}
};
`
)
console.log(`gea program: image ${imageEnd} B, memory ${memoryEnd} B, ${relocs.length} relocations -> ${out}`)
